apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-app
  namespace: default
spec:
  project: default
  source:
    repoURL: git@github.com:yotam-halperin/argocd-crm5-charts.git
    targetRevision: HEAD
    path: ingress-nginx
  destination:
    server: https://kubernetes.default.svc
