apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-app
  namespace: default
spec:
  project: default
  source:
    repoURL: git@github.com:yotam-halperin/argocd-crm5-charts.git
    targetRevision: HEAD
    path: apps/sealed-secrets
  destination:
    server: https://kubernetes.default.svc
